'use client';

import { 
  SandpackLayout,
  SandpackCodeEditor,
  SandpackFileExplorer,
  useSandpack
} from "@codesandbox/sandpack-react";
import { useEffect, useState } from "react";
import { Loader2 } from "lucide-react";
import type { SandpackEditorProps } from "./types";

// Mock data for testing
const MOCK_FILES = {
  '/app/page.tsx': `export default function Home() {
  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-100">
      <div className="text-center space-y-6">
        <h1 className="text-6xl font-bold text-gray-900">
          Welcome to CodeFox
        </h1>
        <p className="text-xl text-gray-600">
          Start building amazing things with AI
        </p>
        <button className="px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors">
          Get Started
        </button>
      </div>
    </div>
  );
}`,
  '/app/layout.tsx': `export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}`,
  '/components/Button.tsx': `interface ButtonProps {
  children: React.ReactNode;
  onClick?: () => void;
  variant?: 'primary' | 'secondary';
}

export function Button({ children, onClick, variant = 'primary' }: ButtonProps) {
  const baseStyles = 'px-4 py-2 rounded-lg font-medium transition-colors';
  const variantStyles = {
    primary: 'bg-blue-600 text-white hover:bg-blue-700',
    secondary: 'bg-gray-200 text-gray-900 hover:bg-gray-300'
  };
  
  return (
    <button 
      onClick={onClick}
      className={\`\${baseStyles} \${variantStyles[variant]}\`}
    >
      {children}
    </button>
  );
}`,
  '/lib/utils.ts': `export function cn(...classes: string[]) {
  return classes.filter(Boolean).join(' ');
}

export function formatDate(date: Date) {
  return new Intl.DateTimeFormat('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  }).format(date);
}`,
  '/styles/globals.css': `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 214, 219, 220;
  --background-end-rgb: 255, 255, 255;
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
    to bottom,
    transparent,
    rgb(var(--background-end-rgb))
  )
  rgb(var(--background-start-rgb));
}`,
  '/README.md': `# CodeFox Local Project

This is a demo project generated by CodeFox.

## Features

- ✨ Modern React with TypeScript
- 🎨 Tailwind CSS styling
- 🚀 Fast development with Vite
- 📦 Component-based architecture

## Get Started

\`\`\`bash
bun install
bun dev
\`\`\`

Built with ❤️ by CodeFox AI
`,
  '/package.json': `{
  "name": "codefox-project",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "next": "^14.0.0"
  },
  "devDependencies": {
    "typescript": "^5.0.0",
    "@types/react": "^18.2.0",
    "@types/node": "^20.0.0",
    "tailwindcss": "^3.3.0"
  }
}`
};

export function SandpackEditor({ projectId }: SandpackEditorProps) {
  const { sandpack } = useSandpack();
  const [files, setFiles] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function loadProjectFiles() {
      // If no projectId, use mock data for testing
      if (!projectId) {
        console.log('[SandpackEditor] No projectId, using mock data for testing');
        setFiles(MOCK_FILES);
        setLoading(false);
        return;
      }

      setLoading(true);
      setError(null);

      try {
        // Get file list
        const listResponse = await fetch(
          `/api/project/files?projectId=${projectId}`
        );
        
        if (!listResponse.ok) {
          throw new Error('Failed to load file list');
        }

        const { files: fileList } = await listResponse.json();

        // Load content for each file
        const fileContents: Record<string, string> = {};
        
        for (const filePath of fileList) {
          try {
            const response = await fetch(
              `/api/project/file?projectId=${projectId}&filePath=${encodeURIComponent(filePath)}`
            );
            
            if (response.ok) {
              const data = await response.json();
              // Sandpack expects files to start with /
              const sandpackPath = filePath.startsWith('/') ? filePath : `/${filePath}`;
              fileContents[sandpackPath] = data.content || '';
            }
          } catch (err) {
            console.warn(`Failed to load file ${filePath}:`, err);
          }
        }

        if (Object.keys(fileContents).length === 0) {
          // Use mock data if no files found
          console.log('[SandpackEditor] No files in project, using mock data');
          setFiles(MOCK_FILES);
        } else {
          setFiles(fileContents);
        }
      } catch (err) {
        console.error('Failed to load project files:', err);
        // Fallback to mock data on error
        console.log('[SandpackEditor] Error loading files, using mock data');
        setFiles(MOCK_FILES);
      } finally {
        setLoading(false);
      }
    }

    loadProjectFiles();
  }, [projectId]);

  // Update sandpack context when files change
  useEffect(() => {
    if (Object.keys(files).length > 0 && sandpack) {
      // Get current files from sandpack
      const currentFiles = sandpack.files;
      const currentFilePaths = Object.keys(currentFiles);
      const newFilePaths = Object.keys(files);

      // Only update if files actually changed
      const filesChanged = 
        currentFilePaths.length !== newFilePaths.length ||
        newFilePaths.some(path => currentFiles[path]?.code !== files[path]);

      if (filesChanged) {
        // Delete removed files
        currentFilePaths.forEach(path => {
          if (!files[path]) {
            sandpack.deleteFile(path);
          }
        });

        // Update or add new files
        Object.entries(files).forEach(([path, code]) => {
          if (!currentFiles[path] || currentFiles[path].code !== code) {
            sandpack.updateFile(path, code);
          }
        });

        // Set first file as active if no active file
        if (!sandpack.activeFile) {
          const firstFile = Object.keys(files)[0];
          if (firstFile) {
            sandpack.openFile(firstFile);
          }
        }
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [files]);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center w-full h-full bg-muted/20">
        <Loader2 className="h-12 w-12 animate-spin text-primary mb-4" />
        <h3 className="text-lg font-semibold">Loading project files...</h3>
        <p className="text-sm text-muted-foreground mt-2">
          This may take a moment
        </p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center w-full h-full bg-muted/20">
        <div className="text-center space-y-2">
          <h3 className="text-lg font-semibold text-red-500">Failed to load project</h3>
          <p className="text-sm text-muted-foreground">{error}</p>
        </div>
      </div>
    );
  }

  if (Object.keys(files).length === 0) {
    return (
      <div className="flex flex-col items-center justify-center w-full h-full bg-muted/20">
        <div className="text-center space-y-2 text-muted-foreground">
          <h3 className="text-lg font-semibold">No files found</h3>
          <p className="text-sm">
            Start chatting to generate project files
          </p>
        </div>
      </div>
    );
  }

  return (
    <SandpackLayout style={{ height: '100%', width: '100%', borderRadius: 0 }}>
      <SandpackFileExplorer style={{ minWidth: 200, maxWidth: 300, height: '100%', maxHeight: 'none' }} />
      <SandpackCodeEditor 
        showTabs
        showLineNumbers
        showInlineErrors
        closableTabs
        style={{ borderRadius: 0, height: '100%' }}
      />
    </SandpackLayout>
  );
}

